services:
  vk_bot_db:
    container_name: "vk_bot_postgres"
    image: postgres:15.4-alpine
    restart: always
    environment:
      POSTGRES_USER: vk_user
      POSTGRES_PASSWORD: vk_pass
      POSTGRES_DB: vk_game
    ports:
      - "9001:5432"
    volumes:
      - /vk_bot/pg_data:/var/lib/postgresql/data
    networks:
      - vkbot-net
  vk_bot_backend:
    build:
      context: .
    container_name: "vk_bot_backend"
    command: bash -c "alembic upgrade head && python main.py"
    ports:
      - "9000:8000"
    depends_on:
      - vk_bot_db
    networks:
      - vkbot-net

networks:
  vkbot-net:
    driver: bridge
