"""add blitz questions

Revision ID: 688526f1c7fd
Revises: d1a6b0292541
Create Date: 2024-12-24 11:07:51.044024

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '688526f1c7fd'
down_revision: Union[str, None] = 'd1a6b0292541'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('blitz_themes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_blitz_themes_title'), 'blitz_themes', ['title'], unique=True)
    op.create_table('blitz_questions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('theme_id', sa.Integer(), nullable=False),
    sa.Column('answer', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['theme_id'], ['blitz_themes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_blitz_questions_title'), 'blitz_questions', ['title'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_blitz_questions_title'), table_name='blitz_questions')
    op.drop_table('blitz_questions')
    op.drop_index(op.f('ix_blitz_themes_title'), table_name='blitz_themes')
    op.drop_table('blitz_themes')
    # ### end Alembic commands ###
