"""add_responsed_player

Revision ID: 74af3c0db5e9
Revises: 10db917dd01c
Create Date: 2024-05-11 18:42:29.890811

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '74af3c0db5e9'
down_revision: Union[str, None] = '10db917dd01c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('games', sa.Column('responsed_player_id', sa.Integer(), nullable=True))
    op.alter_column('games', 'game_stage',
               existing_type=postgresql.ENUM('NOT_START', 'REGISTRATION_GAMERS', 'WAITING_CALLBACK', 'WAITING_ANSWER', 'FINISHED', 'CANCELED', name='gamestage'),
               nullable=False,
               existing_server_default=sa.text("'NOT_START'::gamestage"))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('games', 'game_stage',
               existing_type=postgresql.ENUM('NOT_START', 'REGISTRATION_GAMERS', 'WAITING_CALLBACK', 'WAITING_ANSWER', 'FINISHED', 'CANCELED', name='gamestage'),
               nullable=True,
               existing_server_default=sa.text("'NOT_START'::gamestage"))
    op.drop_column('games', 'responsed_player_id')
    # ### end Alembic commands ###
