"""add blitz game and players

Revision ID: 39fc80a2af87
Revises: 688526f1c7fd
Create Date: 2024-12-28 12:07:46.569449

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '39fc80a2af87'
down_revision: Union[str, None] = '688526f1c7fd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('blitz_game_settings',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('profile_name', sa.String(), nullable=False),
    sa.Column('description', sa.String(length=1000), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('profile_name')
    )
    op.create_table('blitz_players',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('vk_user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('vk_user_id')
    )
    op.create_table('blitz_games',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('conversation_id', sa.Integer(), nullable=True),
    sa.Column('pinned_conversation_message_id', sa.Integer(), nullable=True),
    sa.Column('game_stage', postgresql.ENUM('WAIT_INIT', 'WAITING_ANSWER', 'FINISHED', 'CANCELED', name='blitzgamestage'), nullable=False),
    sa.Column('admin_game_id', sa.Integer(), nullable=True),
    sa.Column('profile_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['profile_id'], ['blitz_game_settings.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('blitz_games')
    op.drop_table('blitz_players')
    op.drop_table('blitz_game_settings')
    # ### end Alembic commands ###
