"""add_game_test

Revision ID: d164e02fd73c
Revises: 2f4f43d4a682
Create Date: 2024-05-09 22:52:12.555446

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd164e02fd73c'
down_revision: Union[str, None] = '2f4f43d4a682'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

def _get_order_status():
    return postgresql.ENUM('NOT_START', 'REGISTRATION_GAMERS', 'WAITING_CALLBACK',
                           'WAITING_ANSWER', 'FINISHED', 'CANCELED', name='game_stages')

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('games',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('conversation_id', sa.Integer(), nullable=True),
    sa.Column('pinned_conversation_message_id', sa.Integer(), nullable=True),
    sa.Column('question_id', sa.Integer(), nullable=False),
    sa.Column('game_stages', sa.Enum('NOT_START', 'REGISTRATION_GAMERS', 'WAITING_CALLBACK', 'WAITING_ANSWER', 'FINISHED', 'CANCELED', 'TEST_STAGE', name='gamestage'), nullable=False),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('players',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vk_user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('game_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('player_answers_games',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('game_id', sa.Integer(), nullable=False),
    sa.Column('answer_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['answer_id'], ['answers.id'], ),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], ),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_index('ix_questions_title', table_name='questions')
    op.create_index(op.f('ix_questions_title'), 'questions', ['title'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_questions_title'), table_name='questions')
    op.create_index('ix_questions_title', 'questions', ['title'], unique=True)
    op.drop_table('player_answers_games')
    op.drop_table('players')
    op.drop_table('games')
    # ### end Alembic commands ###
    _get_order_status().drop(op.get_bind())