"""add constraint table question-game

Revision ID: 76674edd5a4f
Revises: 39fc80a2af87
Create Date: 2024-12-28 12:17:12.436596

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '76674edd5a4f'
down_revision: Union[str, None] = '39fc80a2af87'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('blitz_question_games',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('question_id', sa.Integer(), nullable=False),
    sa.Column('game_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['game_id'], ['blitz_games.id'], ),
    sa.ForeignKeyConstraint(['question_id'], ['blitz_questions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('question_id', 'game_id', name='idx_unique_blitz_question_game')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('blitz_question_games')
    # ### end Alembic commands ###
